name: Build WHY2025 Badge M.2 board FW
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5
          target: esp32p4
          path: .
          command: 'apt update && apt install -y jq && idf.py build merge-bin -o merged.bin -f hex'
      - name: Store binaries as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: meshtastic-why2025-m2-firmware-${{github.sha}}.zip
          overwrite: true
          path: |
            build/merged.bin